### ISSUE TITLE
我运行起来之后登录后台,错误

### ISSUE THREAD

**Issue by aboutdata** [jiekechoo/spring-security-session-redis-user-details-service#2]
错误如下：
我是通过api接口创建的admin/123456/123456

![Uploading QQ截图20150710171006.png…]()

**Comment by aboutdata** [comment]
> 错误如下：
![image](https://cloud.githubusercontent.com/assets/13091938/8615641/0b9aa444-2727-11e5-9231-bc24bdef78ac.png)

**Comment by jiekechoo** [comment]
你需要在 authorities 表中增加 admin / ROLE_ADMIN 记录（原有记录不需要删除），这样你才有 /admin 访问权限。

**Comment by aboutdata** [comment]
> 你需要在 authorities 表中增加 admin / ROLE_ADMIN 记录（原有记录不需要删除），这样你才有 /admin 访问权限。

ok 谢谢@jiekechoo 我试试看
